[project]
name = "nuoiem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.3.3",
    "requests>=2.32.5",
    "unidecode>=1.3.8",
]
